/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
var fibonacciNumbers = [1, 2];
var a = 1;
var b = 2;
var c = 0;
for (var i = 0; a + b < 4000000; i++) {
  c = a + b;
  fibonacciNumbers.push(c);
  a = b;
  b = c;
}

var isEven = function(n) {
  if(n % 2 === 0) {
    return true;
  };
}

var sumEven = 0;
for (var j = 0; j < fibonacciNumbers.length; j++) {
  if (isEven(fibonacciNumbers[j])) {
    sumEven += fibonacciNumbers[j];
  }
}

console.log(sumEven);
--> 4613732
